<a href="https://colab.research.google.com/github/Dheesiga/Bharat-Intern/blob/task-1/Untitled.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import nltk
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer,WordNetLemmatizer
from nltk.tokenize import word_tokenize
import sklearn.metrics as m
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier


In [2]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [4]:
dataset=pd.read_csv('/spam.csv', encoding='latin1')
dataset.head()

v1                                                 v2 Unnamed: 2  \
0  not spam  Go until jurong point, crazy.. Available only ...        NaN   
1  not spam                      Ok lar... Joking wif u oni...        NaN   
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3  not spam  U dun say so early hor... U c already then say...        NaN   
4  not spam  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [5]:
sent=dataset.iloc[:,[1]]['v2']
sent

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: v2, Length: 5572, dtype: object

In [6]:
label=dataset.iloc[:,[0]]['v1']
label

0       not spam
1       not spam
2           spam
3       not spam
4       not spam
          ...   
5567        spam
5568    not spam
5569    not spam
5570    not spam
5571    not spam
Name: v1, Length: 5572, dtype: object

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
label=le.fit_transform(label)
label

array([0, 0, 1, ..., 0, 0, 0])

In [8]:
le.classes_


array(['not spam', 'spam'], dtype=object)

In [9]:
import re
len(set(stopwords.words('english')))
lemma=WordNetLemmatizer()
sent

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: v2, Length: 5572, dtype: object

In [10]:
sentences=[]
for sen in sent:
  senti=re.sub('[^A-Za-z]',' ',sen)
  senti=senti.lower()
  words=word_tokenize(senti)
  word=[lemma.lemmatize(i) for i in words if i not in stopwords.words('english')]
  senti=' '.join(word)
  sentences.append(senti)
sentences[:5]

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though']

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=5000)
features=tfidf.fit_transform(sentences)
features=features.toarray()
features

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
!pip install sklearn

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [21]:
import sklearn.feature_extraction.text as sktext
count_vectorizer = sktext.CountVectorizer()


In [25]:
count_vectorizer.fit(sentences)
feature_names = count_vectorizer.get_feature_names_out()
print(feature_names)

['aa' 'aah' 'aaniye' ... 'zoom' 'zouk' 'zyada']


In [26]:
feature_train,feature_test,label_train,label_test=train_test_split(features,label,test_size=0.2,random_state=7)


In [27]:
model=MultinomialNB()
model.fit(feature_train,label_train)
label_pred=model.predict(feature_test)
label_pred
label_test
m.accuracy_score(label_test,label_pred)

0.9748878923766816

In [28]:
print(m.classification_report(label_test,label_pred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.99       970
           1       1.00      0.81      0.89       145

    accuracy                           0.97      1115
   macro avg       0.99      0.90      0.94      1115
weighted avg       0.98      0.97      0.97      1115



In [29]:
print(m.confusion_matrix(label_test,label_pred))

[[970   0]
 [ 28 117]]
